# Application
spring.application.name=ShopKart
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopkart
spring.datasource.hikari.schema=dataspace
spring.datasource.username=admin
spring.datasource.password=password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.property-naming-strategy=SNAKE_CASE

# Redis cache
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379

# JWT
shopkart.jwt.expiration-ms=3600000
